## Tableaux
NumPy propose une structure de données populaire, les tableaux (de type array), sur lesquels il est possible d’effectuer de manière efficace des calculs. Les tableaux sont une structure notamment utile pour effectuer des opérations statistiques basiques ainsi que de la génération pseudo-aléatoire de nombres.

La stucture des tableaux ressemble à celle des listes, mais ces dernières sont moins rapides à être traitées et utilisent davantage de mémoire. Le gain de vitesse de traitement des tableaux en NumPy vient du fait que les données sont stockées dans des blocs contigus de mémoire, facilitant ainsi les accès en lecture.

In [38]:
import numpy as np

### Création

La création d’un tableau peut s’effectuer avec la méthode array(), à partir d’une liste, comme nous venon de le faire :

In [39]:
liste = [1,2,4]
tableau = np.array(liste)
print(tableau)

[1 2 4]


Si on fournit à array() une liste de listes imbriquées de même longueur, un tableau multidimensionnel sera créé :


In [40]:
liste_2 = [ [1,2,3], [4,5,6] ]
tableau_2 = np.array(liste_2)
print(tableau_2)

[[1 2 3]
 [4 5 6]]


Les tableaux peuvent aussi être créés à partir de n-uplets :



In [41]:
nuplet = (1, 2, 3)
tableau = np.array(nuplet)
print(tableau)

[1 2 3]


Un tableau en dimension 1 peut être changé en tableau en dimension 2 (si possible), en modifiant son attribut shape :



In [46]:
tableau = np.array([3, 2, 5, 1, 6, 5])
tableau.shape = (6,1)
print(tableau)

[[3]
 [2]
 [5]
 [1]
 [6]
 [5]]


### Quelques fonctions générant des array


Certaines fonctions de NumPy produisent des tableaux pré-remplis. C’est le cas de la fonction zeros(). Quand on lui fournit une valeur entière n, la fonction zeros() créé un tableau à une dimension, avec n 0 :

In [47]:
print( np.zeros(4) )

[0. 0. 0. 0.]


On peut préciser le type des zéros (par exemple int, int32, int64, float, float32, float64, etc.), à l’aide du paramètre dtype

In [11]:
print( np.zeros(4, dtype = "int") )

[0 0 0 0]


Le type des éléments d’un tableau est indiqué dans l’attribut dtype :



In [13]:
x = np.zeros(4, dtype = "int")
print(x, x.dtype)

[0 0 0 0] int32


Il est par ailleurs possible de convertir le type des éléments dans un un autre type, à l’aide de la méthode astype()

In [15]:
y = x.astype("float")
print(x, x.dtype)

[0 0 0 0] int32


In [16]:
print(y, y.dtype)


[0. 0. 0. 0.] float64


Quand on lui fournit un n-uplet de longueur supérieure à 1, zeros() créé un tableau à plusieurs dimensions :

In [17]:
print( np.zeros((2, 3)) )


[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
print( np.zeros((2, 3, 4)) )


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


La fonction empty() de Numpy retourne également un tableau sur le même principe que zeros(), mais sans initialiser les valeurs à l’intérieur.

In [19]:
print( np.empty((2, 3), dtype = "int") )


[[0 0 0]
 [0 0 0]]


La fonction ones() de Numpy retourne le même genre de tableaux, avec des 1 en valeurs initialisées :



In [20]:
print( np.ones((2, 3), dtype = "float") )


[[1. 1. 1.]
 [1. 1. 1.]]


Pour choisir une valeur spécifique pour l’initialisation, on peut utiliser la fonction full() de Numpy :



In [21]:
print( np.full((2, 3), 10, dtype = "float") )


[[10. 10. 10.]
 [10. 10. 10.]]


In [22]:
print( np.full((2, 3), np.inf) )


[[inf inf inf]
 [inf inf inf]]


La fonction eye() de Numpy créé un tableau à deux dimensions dans laquelle tous les éléments sont initalisés à zéro, sauf ceux de la diagonale initialisés à 1 :

In [23]:
print( np.eye(2, dtype="int64") )

[[1 0]
 [0 1]]


En modifiant le paramètre mot-clé k, on peut décaler la diagonale :



In [24]:
print( np.eye(3, k=-1) )


[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


La fonction identity() de Numpy créé quant à elle une matrice identité sous la forme d’un tableau :



In [25]:
print( np.identity(3, dtype = "int") )

[[1 0 0]
 [0 1 0]
 [0 0 1]]


La fonction arange() de Numpy permet de générer une séquence de nombres séparés par un interval fixe, le tout stocké dans un tableau. La syntaxe est la suivante :

np.arange( start, stop, step, dtype )
avec start la valeur de départ, stop celle d’arrivée, step le pas, l’espacement entre les nombres de la séquence et dtype le type des nombres :

In [26]:
print( np.arange(5) )


[0 1 2 3 4]


In [27]:
print( np.arange(2, 5) )


[2 3 4]


In [28]:
print( np.arange(2, 10, 2) )


[2 4 6 8]


## Dimensions
Pour connaître la dimension d’un tableau, on peut afficher la valeur de l’attribut ndim :

In [29]:
print("ndim tableau : ", tableau.ndim)

ndim tableau :  2


In [30]:
print("ndim tableau_2 : ", tableau_2.ndim)


ndim tableau_2 :  2


Le nombre d’éléments dans le tableau peut s’obtenir par l’attribut size ou par la fonction size() de Numpy :

In [31]:
print("size tableau : ", tableau.size)

size tableau :  6


In [ ]:
print("size tableau_2 : ", tableau_2.size)

In [32]:
print("np.size(tableau) :", np.size(tableau))

np.size(tableau) : 6


L’attribut shape retourne un n-uplet indiquant la longueur pour chaque dimension du tableau :


In [33]:
print("size tableau : ", tableau.shape)

size tableau :  (3, 2)


In [34]:
print("size tableau_2 : ", tableau_2.shape)

size tableau_2 :  (2, 3)


### Extraction des éléments d’un tableau
L’accès aux éléments d’un tableau se fait de la même manière que pour les listes. La syntaxe est la suivante :

tableau[lower:upper:step]
avec lower la borne inférieur de la plage d’indices, upper la plage supérieur, et step l’espacement entre les valeurs.

Lorsque lower n’est pas précisé, le premier élément (indicé 0) est considéré comme la valeur attribuée à lower.
Lorsque upper n’est pas précisé, le dernier élément est considéré comme la valeur attribuée à upper.
Lorsque step n’est pas précisé, un pas de 1 est attribué par défaut.
Reprenons rapidement quelques exemples, en s’appuyant sur deux objets : un tableau de dimension 1, et un second de dimension 2.

In [37]:
tableau_1 = np.arange(1,13)
tableau_2 = [ [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
tableau_2 = np.array(tableau_2)